---
# Install Clickhouse
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - role: clickhouse

# Install Vector
- name: Install Vector
  hosts: vector
  roles:
    - role: vector-role

# Install Lighthouse
- name: Install Lighthouse
  hosts: lighthouse
  roles:
    - role: lighthouse-role
