---
#clickhouse
  - src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse 
#vectore
  - src: https://github.com/stensil4rt/vector-role_net.git
    scm: git
    version: "main"
    name: vector-role
#lighthouse
  - src: https://github.com/stensil4rt/lighthouse-role_net.git
    scm: git
    version: "main"
    name: lighthouse-role
