---
ansible_user            : ansible
ansible_ssh_pass        : PassSuperSecret)
ansible_become: yes 
ansible_become_method: sudo
ansible_become_pass: "PassSuperSecret)"

clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static


